[package]
name = "nlookup"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { version = "0.4.0", features = [ "asm" ] }
ark-ec = { version = "0.4.0", default-features = false }
ark-poly = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", default-features = false }
ark-relations = { version = "0.4.0", default-features = false }
ark-r1cs-std = { version = "0.4.0", default-features = false }
ark-pallas = { version = "0.4.0", features = ["scalar_field"] }
ark-std = { version = "0.4.0", default-features = false }
ark-pallas = { version = "0.4.0", features = ["scalar_field"] }

[profile.test]
opt-level = 3

