name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List dependencies and version
      run: |
        cargo --version
        rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Get ppot
      run: wget https://pse-trusted-setup-ppot.s3.eu-central-1.amazonaws.com/pot28_0080/ppot_0080_20.ptau
    - name: Run tests
      run: cargo test --verbose
    - name: Format
      run: cargo fmt -- --check
